### ISSUE TITLE
Make the description more meaningful for system route pass expiry

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#305]
Label it as "[System Event] Expire route credits from [Original Amount] to [Final Amount] after x days for credits purchased on x with transaction ID x"

Now it does not really make sense.

![image](https://user-images.githubusercontent.com/22762719/30108427-e3652a90-9334-11e7-8ec9-0e1fb5764485.png)

**Comment by LoneRifle** [comment]
I'm in favour of the last two approaches. Shall we close this issue and create new ones in frontend and server?

**Comment by chuasweechin** [comment]
Erm what is the 2 approaches you mentioned?

**Comment by LoneRifle** [comment]
The ones in your earlier comment..

**Comment by chuasweechin** [comment]
Oh right. Yes, the last 2 approach is the best.
You can proceed to close this and open 2 different issues.

**Comment by LoneRifle** [comment]
Superseded by abovementioned issues
