### ISSUE TITLE
Allow operator to void ticket in admin view

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#326]
Create a void button for tickets. See the button position in red below.
![image](https://user-images.githubusercontent.com/22762719/31749302-c37c185e-b4ab-11e7-9607-b7348ab7931f.png)

**Comment by LoneRifle** [comment]
Do I have time to rewrite the bookings page? the pagination irks me in particular, and we should make a habit of doing changes only on Vue code anyway.

**Comment by chuasweechin** [comment]
Lol if u got time, i dun mind. The pagination is a problem but we can still
leave with it.

**Comment by LoneRifle** [comment]
Fixed by #334
