### ISSUE TITLE
[Bug] Admin View has a random issue whereby route is not loaded. It would appear the query have some issues. This happens randomly

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#332]
![image](https://user-images.githubusercontent.com/22762719/32063732-856ee6f4-baaa-11e7-8056-6af138a167fd.png)

**Comment by LoneRifle** [comment]
503 is service unavailable, which indicates that the admin service is hitting capacity problems. Likely related to the download csv feature.

**Comment by LoneRifle** [comment]
There are a couple of Network Error entries in the logs. Probably related to the recent stability problems that we have had when we made the Download CSV link available.

**Comment by chuasweechin** [comment]
I dun quite understand why the csv download affect only the route view and
not all aspect of admin view. When i check bookings and route passes,
everything looks ok

**Comment by chuasweechin** [comment]
Should we take away download csv for route pass first? Cause route page is
pretty improtant for ops.

We will put it back when it is more stable

**Comment by LoneRifle** [comment]
We could upgrade the dyno as an alternative, though bear in mind that's $25/mth compared to the $7 we are currently paying

**Comment by chuasweechin** [comment]
That is one way. I am just wondering why would the most record heavy
booking csv is ok compare to route pass. Cause rightfully, grab cant be
spamming the download of csv too

**Comment by LoneRifle** [comment]
It isn't okay - the csv dump is _causing_ the subsequent stability issues. My worry is that the server dyno isn't doing proper cleanup after something like that happens, and this has knock-on effects. 

I've upgraded the dyno to the standard 1X for now for stability sake and giving its increasing importance. Closing for now.
