### ISSUE TITLE
[Bug] Route trip creation fail

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#333]
![image](https://user-images.githubusercontent.com/22762719/32064767-6575ce5a-baad-11e7-8a89-389263e4fbcf.png)
![image](https://user-images.githubusercontent.com/22762719/32064801-7ca201a2-baad-11e7-83fc-fa2d181ff2d0.png)

**Comment by LoneRifle** [comment]
403 indicates that your tokens expired. This is probably related to the recent changes we made to auth0 requiring people to sign in again.

**Comment by chuasweechin** [comment]
I got try that. All other modules of admin view was ok when i was creating
route last night

**Comment by LoneRifle** [comment]
I'll probably need you to demonstrate how to reproduce the bug then..

**Comment by chuasweechin** [comment]
I am on leave today, but what u can do is, go to C208 and edit that trip
inside. This bug will consistently happening. I try a few times last night

**Comment by LoneRifle** [comment]
Did you mean C201? There is no route corresponding to C208.

**Comment by chuasweechin** [comment]
Sry, try c228 instead

**Comment by LoneRifle** [comment]
Unable to reproduce, trips created without issue
<img width="1645" alt="screen shot 2017-10-27 at 8 43 48 am" src="https://user-images.githubusercontent.com/10572368/32083144-31c1d568-baf3-11e7-9beb-ebce798da866.png">

Might be to do with auth0 stability issues that are currently ongoing, and as reported on our monitoring tool
