### ISSUE TITLE
routePasses.vue - add txn description column

### ISSUE THREAD

**Issue by LoneRifle** [datagovsg/beeline-admin#335]
The route passes page currently does not display the description of the transaction. This can be done by debugging the route passes page, inspecting the server response and making the appropriate one-line change to add the new field to the table.

**Comment by chuasweechin** [comment]
Proposed to do with the description below:
Route pass purchase (Original Route Pass Txn #xxxxxxx)

**Comment by LoneRifle** [comment]
@chuasweechin are you referring to the Bookings section? That's a separate issue to this one =)

**Comment by chuasweechin** [comment]
Ohhhh okok.
