### ISSUE TITLE
Delete Stop Button does not work. Seems like no API is called

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#344]
To access this page, go to a route > edit trip > add/edit stop/ > choose a stop

We are unable to delete incorrect stop now.

![image](https://user-images.githubusercontent.com/22762719/32788556-7d2127d4-c994-11e7-8c3e-77c764ab0e02.png)

**Comment by chuasweechin** [comment]
![image](https://user-images.githubusercontent.com/22762719/32956954-5e67f030-cbf5-11e7-8f16-ba4e4b77d3cb.png)
 
Pop up modal is shown, however stop is not deleted. It appear nothing happened

**Comment by LoneRifle** [comment]
Server was swallowing an exception thrown - you cannot delete stops if they have been previously associated with trips, but you never get that because the exception that gets triggered never gets returned to you. 

datagovsg/beeline-server#41 filed, try again once merged

**Comment by chuasweechin** [comment]
Alright. So for stops that has no assiocation trip, it should be deletable
right?

**Comment by LoneRifle** [comment]
Yup
