### ISSUE TITLE
refactor the content for ticket purchase using route pass

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#350]
![image](https://user-images.githubusercontent.com/22762719/32956423-b00d031e-cbf3-11e7-89bf-e22a73c0fc8e.png)

Proposed to put as "Purchase **using** route pass (rp-xxx)" with **<per pass discount>** discount 
- [txn xxxxx]

Changes:
- replace "of" with "using"
- rephrase the wording to make the discount portion more readable
- show per pass discount instead of bulk discount
- make the txn clickable to link back to original route pass transaction for easy tractability

**Comment by LoneRifle** [comment]
Eh, "Purchase of route pass" is coming directly from the original transaction's description. Do you want me to construct a completely different description to reflect the fact that we are referencing it from a ticket booking?

**Comment by chuasweechin** [comment]
Oh i get it. But the discount element also? I recall in route pass,
discount is showing as a per pass basis

**Comment by LoneRifle** [comment]
that's largely because I have access to the other fields. I _guess_ I can construct an object to return to admin containing the route pass purchase metadata and then we construct something out of it. I'll work on this approach for now.
