### ISSUE TITLE
[BUG] Booking count error in Admin View Booking Calendar

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-admin#361]
I was looking at 1 Jan data and, there are zero records on the CSV for all outbound buses to Sengkang (Z04A & Z04B). At times, it shows 6 persons, and now after refeshing, it shows 63, which is impossible

There is a bug with the booking count on the calendar for public holiday
![image](https://user-images.githubusercontent.com/22762719/35963802-e3763d72-0cf0-11e8-904a-5f1226f076a1.png)

**Comment by LoneRifle** [comment]
Fixed in 691c3de
